-- MySQL Script generated by MySQL Workbench
-- Sun Nov  8 12:07:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`UNIFAMILIAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UNIFAMILIAR` (
  `idUNIFAMILIAR` INT NOT NULL,
  PRIMARY KEY (`idUNIFAMILIAR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CONSTRUCCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CONSTRUCCION` (
  `Coordendas geograficas` INT NOT NULL,
  `idConstruccion` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NULL,
  `UNIFAMILIAR_idUNIFAMILIAR` INT NOT NULL,
  PRIMARY KEY (`Coordendas geograficas`, `idConstruccion`, `UNIFAMILIAR_idUNIFAMILIAR`),
  INDEX `fk_CONSTRUCCION_UNIFAMILIAR1_idx` (`UNIFAMILIAR_idUNIFAMILIAR` ASC) VISIBLE,
  CONSTRAINT `fk_CONSTRUCCION_UNIFAMILIAR1`
    FOREIGN KEY (`UNIFAMILIAR_idUNIFAMILIAR`)
    REFERENCES `mydb`.`UNIFAMILIAR` (`idUNIFAMILIAR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BLOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BLOQUE` (
  `idBLOQUE` INT NOT NULL,
  `CONSTRUCCION_Coordendas geograficas` INT NOT NULL,
  `CONSTRUCCION_idConstruccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBLOQUE`, `CONSTRUCCION_Coordendas geograficas`, `CONSTRUCCION_idConstruccion`),
  INDEX `fk_BLOQUE_CONSTRUCCION1_idx` (`CONSTRUCCION_Coordendas geograficas` ASC, `CONSTRUCCION_idConstruccion` ASC) VISIBLE,
  CONSTRAINT `fk_BLOQUE_CONSTRUCCION1`
    FOREIGN KEY (`CONSTRUCCION_Coordendas geograficas` , `CONSTRUCCION_idConstruccion`)
    REFERENCES `mydb`.`CONSTRUCCION` (`Coordendas geograficas` , `idConstruccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONA` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `PERSONA_DNI` INT NOT NULL,
  `UNIFAMILIAR_idUNIFAMILIAR` INT NOT NULL,
  PRIMARY KEY (`DNI`, `PERSONA_DNI`, `UNIFAMILIAR_idUNIFAMILIAR`),
  INDEX `fk_PERSONA_PERSONA1_idx` (`PERSONA_DNI` ASC) VISIBLE,
  INDEX `fk_PERSONA_UNIFAMILIAR1_idx` (`UNIFAMILIAR_idUNIFAMILIAR` ASC) VISIBLE,
  CONSTRAINT `fk_PERSONA_PERSONA1`
    FOREIGN KEY (`PERSONA_DNI`)
    REFERENCES `mydb`.`PERSONA` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSONA_UNIFAMILIAR1`
    FOREIGN KEY (`UNIFAMILIAR_idUNIFAMILIAR`)
    REFERENCES `mydb`.`UNIFAMILIAR` (`idUNIFAMILIAR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PISO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PISO` (
  `Letra` INT NOT NULL,
  `Planta` INT NOT NULL,
  `BLOQUE_idBLOQUE` INT NOT NULL,
  `BLOQUE_CONSTRUCCION_Coordendas geograficas` INT NOT NULL,
  `BLOQUE_CONSTRUCCION_idConstruccion` VARCHAR(45) NOT NULL,
  `PERSONA_DNI` INT NOT NULL,
  `PERSONA_PERSONA_DNI` INT NOT NULL,
  `PERSONA_UNIFAMILIAR_idUNIFAMILIAR` INT NOT NULL,
  PRIMARY KEY (`Letra`, `Planta`, `BLOQUE_idBLOQUE`, `BLOQUE_CONSTRUCCION_Coordendas geograficas`, `BLOQUE_CONSTRUCCION_idConstruccion`, `PERSONA_DNI`, `PERSONA_PERSONA_DNI`, `PERSONA_UNIFAMILIAR_idUNIFAMILIAR`),
  INDEX `fk_PISO_BLOQUE1_idx` (`BLOQUE_idBLOQUE` ASC, `BLOQUE_CONSTRUCCION_Coordendas geograficas` ASC, `BLOQUE_CONSTRUCCION_idConstruccion` ASC) VISIBLE,
  INDEX `fk_PISO_PERSONA1_idx` (`PERSONA_DNI` ASC, `PERSONA_PERSONA_DNI` ASC, `PERSONA_UNIFAMILIAR_idUNIFAMILIAR` ASC) VISIBLE,
  CONSTRAINT `fk_PISO_BLOQUE1`
    FOREIGN KEY (`BLOQUE_idBLOQUE` , `BLOQUE_CONSTRUCCION_Coordendas geograficas` , `BLOQUE_CONSTRUCCION_idConstruccion`)
    REFERENCES `mydb`.`BLOQUE` (`idBLOQUE` , `CONSTRUCCION_Coordendas geograficas` , `CONSTRUCCION_idConstruccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PISO_PERSONA1`
    FOREIGN KEY (`PERSONA_DNI` , `PERSONA_PERSONA_DNI` , `PERSONA_UNIFAMILIAR_idUNIFAMILIAR`)
    REFERENCES `mydb`.`PERSONA` (`DNI` , `PERSONA_DNI` , `UNIFAMILIAR_idUNIFAMILIAR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONA` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Área` VARCHAR(45) NULL,
  `Código postal` INT NULL,
  `Concejal` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CALLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CALLE` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Número` INT NULL,
  `CONSTRUCCION_Coordendas geograficas` INT NOT NULL,
  `CONSTRUCCION_idConstruccion` VARCHAR(45) NOT NULL,
  `CONSTRUCCION_UNIFAMILIAR_idUNIFAMILIAR` INT NOT NULL,
  `ZONA_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `CONSTRUCCION_Coordendas geograficas`, `CONSTRUCCION_idConstruccion`, `CONSTRUCCION_UNIFAMILIAR_idUNIFAMILIAR`, `ZONA_Nombre`),
  INDEX `fk_CALLE_CONSTRUCCION1_idx` (`CONSTRUCCION_Coordendas geograficas` ASC, `CONSTRUCCION_idConstruccion` ASC, `CONSTRUCCION_UNIFAMILIAR_idUNIFAMILIAR` ASC) VISIBLE,
  INDEX `fk_CALLE_ZONA1_idx` (`ZONA_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_CALLE_CONSTRUCCION1`
    FOREIGN KEY (`CONSTRUCCION_Coordendas geograficas` , `CONSTRUCCION_idConstruccion` , `CONSTRUCCION_UNIFAMILIAR_idUNIFAMILIAR`)
    REFERENCES `mydb`.`CONSTRUCCION` (`Coordendas geograficas` , `idConstruccion` , `UNIFAMILIAR_idUNIFAMILIAR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CALLE_ZONA1`
    FOREIGN KEY (`ZONA_Nombre`)
    REFERENCES `mydb`.`ZONA` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
