-- MySQL Script generated by MySQL Workbench
-- Mon Nov  9 14:47:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONA` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Área` VARCHAR(45) NULL,
  `Código postal` INT NULL,
  `Concejal` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CALLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CALLE` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Número` INT NULL,
  `Tipo` VARCHAR(45) NULL,
  `ZONA_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`),
  INDEX `fk_CALLE_ZONA1_idx` (`ZONA_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_CALLE_ZONA1`
    FOREIGN KEY (`ZONA_Nombre`)
    REFERENCES `mydb`.`ZONA` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CONSTRUCCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CONSTRUCCION` (
  `Coordendas geograficas` INT NOT NULL,
  `idConstruccion` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NULL,
  `NumeroPisos` INT NULL,
  `NumeroPersonas` INT NULL,
  `CALLE_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idConstruccion`, `CALLE_Nombre`),
  UNIQUE INDEX `Coordendas geograficas_UNIQUE` (`Coordendas geograficas` ASC) VISIBLE,
  INDEX `fk_CONSTRUCCION_CALLE1_idx` (`CALLE_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_CONSTRUCCION_CALLE1`
    FOREIGN KEY (`CALLE_Nombre`)
    REFERENCES `mydb`.`CALLE` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BLOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BLOQUE` (
  `CONSTRUCCION_idConstruccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CONSTRUCCION_idConstruccion`),
  INDEX `fk_BLOQUE_CONSTRUCCION1_idx` (`CONSTRUCCION_idConstruccion` ASC) VISIBLE,
  CONSTRAINT `fk_BLOQUE_CONSTRUCCION1`
    FOREIGN KEY (`CONSTRUCCION_idConstruccion`)
    REFERENCES `mydb`.`CONSTRUCCION` (`idConstruccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PISO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PISO` (
  `Letra` INT NOT NULL,
  `Planta` INT NOT NULL,
  `BLOQUE_CONSTRUCCION_idConstruccion` VARCHAR(45) NOT NULL,
  `Dueño` INT NULL,
  PRIMARY KEY (`Letra`, `BLOQUE_CONSTRUCCION_idConstruccion`, `Planta`),
  INDEX `fk_PISO_BLOQUE1_idx` (`BLOQUE_CONSTRUCCION_idConstruccion` ASC) VISIBLE,
  UNIQUE INDEX `Planta_UNIQUE` (`Planta` ASC) VISIBLE,
  INDEX `dueño_idx` (`Dueño` ASC) VISIBLE,
  CONSTRAINT `fk_PISO_BLOQUE1`
    FOREIGN KEY (`BLOQUE_CONSTRUCCION_idConstruccion`)
    REFERENCES `mydb`.`BLOQUE` (`CONSTRUCCION_idConstruccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dueño`
    FOREIGN KEY (`Dueño`)
    REFERENCES `mydb`.`PERSONA` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONA` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `PERSONA_DNI` INT NOT NULL,
  `unifamiliar` VARCHAR(45) NULL,
  `PISO_Letra` INT NOT NULL,
  `PISO_BLOQUE_CONSTRUCCION_idConstruccion` VARCHAR(45) NOT NULL,
  `PISO_Planta` INT NOT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `fk_PERSONA_PERSONA1_idx` (`PERSONA_DNI` ASC) VISIBLE,
  INDEX `habitaUnifamiliar_idx` (`unifamiliar` ASC) VISIBLE,
  INDEX `fk_PERSONA_PISO1_idx` (`PISO_Letra` ASC, `PISO_BLOQUE_CONSTRUCCION_idConstruccion` ASC, `PISO_Planta` ASC) VISIBLE,
  CONSTRAINT `fk_PERSONA_PERSONA1`
    FOREIGN KEY (`PERSONA_DNI`)
    REFERENCES `mydb`.`PERSONA` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `habitaUnifamiliar`
    FOREIGN KEY (`unifamiliar`)
    REFERENCES `mydb`.`UNIFAMILIAR` (`CONSTRUCCION_idConstruccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSONA_PISO1`
    FOREIGN KEY (`PISO_Letra` , `PISO_BLOQUE_CONSTRUCCION_idConstruccion` , `PISO_Planta`)
    REFERENCES `mydb`.`PISO` (`Letra` , `BLOQUE_CONSTRUCCION_idConstruccion` , `Planta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UNIFAMILIAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UNIFAMILIAR` (
  `CONSTRUCCION_idConstruccion` VARCHAR(45) NOT NULL,
  `dueño` INT NULL,
  PRIMARY KEY (`CONSTRUCCION_idConstruccion`),
  INDEX `fk_UNIFAMILIAR_CONSTRUCCION1_idx` (`CONSTRUCCION_idConstruccion` ASC) VISIBLE,
  INDEX `dueño_idx` (`dueño` ASC) VISIBLE,
  CONSTRAINT `fk_UNIFAMILIAR_CONSTRUCCION1`
    FOREIGN KEY (`CONSTRUCCION_idConstruccion`)
    REFERENCES `mydb`.`CONSTRUCCION` (`idConstruccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dueño`
    FOREIGN KEY (`dueño`)
    REFERENCES `mydb`.`PERSONA` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
