-- MySQL Script generated by MySQL Workbench
-- Fri Nov  6 22:48:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EmpresaViveros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EmpresaViveros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EmpresaViveros` DEFAULT CHARACTER SET utf8 ;
USE `EmpresaViveros` ;

-- -----------------------------------------------------
-- Table `EmpresaViveros`.`VIVEROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaViveros`.`VIVEROS` (
  `idViveros` INT NOT NULL,
  `Ubicación` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Hora de cierre` TIME NULL,
  `Hora apertura` TIME NULL,
  PRIMARY KEY (`idViveros`, `Ubicación`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmpresaViveros`.`ZONAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaViveros`.`ZONAS` (
  `Nombre` VARCHAR(45) NOT NULL,
  `VIVEROS_idViveros` INT NOT NULL,
  `VIVEROS_Ubicación` VARCHAR(45) NOT NULL,
  INDEX `fk_ZONAS_VIVEROS_idx` (`VIVEROS_idViveros` ASC, `VIVEROS_Ubicación` ASC) VISIBLE,
  PRIMARY KEY (`Nombre`),
  CONSTRAINT `fk_ZONAS_VIVEROS`
    FOREIGN KEY (`VIVEROS_idViveros` , `VIVEROS_Ubicación`)
    REFERENCES `EmpresaViveros`.`VIVEROS` (`idViveros` , `Ubicación`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmpresaViveros`.`EMPLEADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaViveros`.`EMPLEADOS` (
  `SeguridadSocial` INT NOT NULL,
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `TipoContrato` VARCHAR(45) NULL,
  `FechaInicio` DATE NULL,
  `FechaFin` DATE NULL,
  `ZONAS_CodigoBarras` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SeguridadSocial`, `DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmpresaViveros`.`ZONAS_has_EMPLEADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaViveros`.`ZONAS_has_EMPLEADOS` (
  `ZONAS_Nombre` VARCHAR(45) NOT NULL,
  `EMPLEADOS_SeguridadSocial` INT NOT NULL,
  `EMPLEADOS_DNI` INT NOT NULL,
  PRIMARY KEY (`ZONAS_Nombre`, `EMPLEADOS_SeguridadSocial`, `EMPLEADOS_DNI`),
  INDEX `fk_ZONAS_has_EMPLEADOS_EMPLEADOS1_idx` (`EMPLEADOS_SeguridadSocial` ASC, `EMPLEADOS_DNI` ASC) VISIBLE,
  INDEX `fk_ZONAS_has_EMPLEADOS_ZONAS1_idx` (`ZONAS_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_ZONAS_has_EMPLEADOS_ZONAS1`
    FOREIGN KEY (`ZONAS_Nombre`)
    REFERENCES `EmpresaViveros`.`ZONAS` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZONAS_has_EMPLEADOS_EMPLEADOS1`
    FOREIGN KEY (`EMPLEADOS_SeguridadSocial` , `EMPLEADOS_DNI`)
    REFERENCES `EmpresaViveros`.`EMPLEADOS` (`SeguridadSocial` , `DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmpresaViveros`.`CLIENTES_FIDELIZADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaViveros`.`CLIENTES_FIDELIZADOS` (
  `DNI` INT NOT NULL,
  `CodigoFidelizacion` INT NOT NULL,
  `NumTarjetaCredito` INT NOT NULL,
  PRIMARY KEY (`DNI`, `CodigoFidelizacion`, `NumTarjetaCredito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmpresaViveros`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaViveros`.`PEDIDO` (
  `idPedido` INT NOT NULL,
  `Fecha` DATE NULL,
  `ZONAS_has_EMPLEADOS_ZONAS_Nombre` VARCHAR(45) NOT NULL,
  `ZONAS_has_EMPLEADOS_EMPLEADOS_SeguridadSocial` INT NOT NULL,
  `ZONAS_has_EMPLEADOS_EMPLEADOS_DNI` INT NOT NULL,
  `CLIENTES_FIDELIZADOS_DNI` INT NOT NULL,
  `CLIENTES_FIDELIZADOS_CodigoFidelizacion` INT NOT NULL,
  `CLIENTES_FIDELIZADOS_NumTarjetaCredito` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `CLIENTES_FIDELIZADOS_DNI`, `CLIENTES_FIDELIZADOS_CodigoFidelizacion`, `CLIENTES_FIDELIZADOS_NumTarjetaCredito`),
  INDEX `fk_PEDIDO_ZONAS_has_EMPLEADOS1_idx` (`ZONAS_has_EMPLEADOS_ZONAS_Nombre` ASC, `ZONAS_has_EMPLEADOS_EMPLEADOS_SeguridadSocial` ASC, `ZONAS_has_EMPLEADOS_EMPLEADOS_DNI` ASC) VISIBLE,
  INDEX `fk_PEDIDO_CLIENTES_FIDELIZADOS1_idx` (`CLIENTES_FIDELIZADOS_DNI` ASC, `CLIENTES_FIDELIZADOS_CodigoFidelizacion` ASC, `CLIENTES_FIDELIZADOS_NumTarjetaCredito` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_ZONAS_has_EMPLEADOS1`
    FOREIGN KEY (`ZONAS_has_EMPLEADOS_ZONAS_Nombre` , `ZONAS_has_EMPLEADOS_EMPLEADOS_SeguridadSocial` , `ZONAS_has_EMPLEADOS_EMPLEADOS_DNI`)
    REFERENCES `EmpresaViveros`.`ZONAS_has_EMPLEADOS` (`ZONAS_Nombre` , `EMPLEADOS_SeguridadSocial` , `EMPLEADOS_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_CLIENTES_FIDELIZADOS1`
    FOREIGN KEY (`CLIENTES_FIDELIZADOS_DNI` , `CLIENTES_FIDELIZADOS_CodigoFidelizacion` , `CLIENTES_FIDELIZADOS_NumTarjetaCredito`)
    REFERENCES `EmpresaViveros`.`CLIENTES_FIDELIZADOS` (`DNI` , `CodigoFidelizacion` , `NumTarjetaCredito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmpresaViveros`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaViveros`.`PRODUCTO` (
  `CodigoBarras` INT NOT NULL,
  `Caducidad` DATE NULL,
  `Tipo` VARCHAR(45) NULL,
  `Precio` FLOAT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Stock` INT NULL,
  PRIMARY KEY (`CodigoBarras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmpresaViveros`.`ZONAS_has_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaViveros`.`ZONAS_has_PRODUCTO` (
  `ZONAS_Nombre` VARCHAR(45) NOT NULL,
  `PRODUCTO_CodigoBarras` INT NOT NULL,
  PRIMARY KEY (`ZONAS_Nombre`, `PRODUCTO_CodigoBarras`),
  INDEX `fk_ZONAS_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_CodigoBarras` ASC) VISIBLE,
  INDEX `fk_ZONAS_has_PRODUCTO_ZONAS1_idx` (`ZONAS_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_ZONAS_has_PRODUCTO_ZONAS1`
    FOREIGN KEY (`ZONAS_Nombre`)
    REFERENCES `EmpresaViveros`.`ZONAS` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZONAS_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_CodigoBarras`)
    REFERENCES `EmpresaViveros`.`PRODUCTO` (`CodigoBarras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmpresaViveros`.`PEDIDO_has_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaViveros`.`PEDIDO_has_PRODUCTO` (
  `PEDIDO_idPedido` INT NOT NULL,
  `PRODUCTO_CodigoBarras` INT NOT NULL,
  PRIMARY KEY (`PEDIDO_idPedido`, `PRODUCTO_CodigoBarras`),
  INDEX `fk_PEDIDO_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_CodigoBarras` ASC) VISIBLE,
  INDEX `fk_PEDIDO_has_PRODUCTO_PEDIDO1_idx` (`PEDIDO_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_has_PRODUCTO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idPedido`)
    REFERENCES `EmpresaViveros`.`PEDIDO` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_CodigoBarras`)
    REFERENCES `EmpresaViveros`.`PRODUCTO` (`CodigoBarras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
