INSERT INTO PERSONA (DNI, Nombre, PERSONA_DNI, unifamiliar, PISO_Letra, PISO_BLOQUE_CONSTRUCCION_IdConstruccion, PISO_Planta,
UNIFAMILIAR_CONSTRUCCION_idConstruccion, UNIFAMILIAR_CONSTRUCCION_CALLE_Nombre) VALUES (333, 'Vic', 222, 'npi', NULL, NULL, NULL, 1, 'holi');

INSERT INTO PERSONA (DNI, Nombre, PERSONA_DNI, unifamiliar, PISO_Letra, PISO_BLOQUE_CONSTRUCCION_IdConstruccion, PISO_Planta,
UNIFAMILIAR_CONSTRUCCION_idConstruccion, UNIFAMILIAR_CONSTRUCCION_CALLE_Nombre) VALUES (222, 'Sergio', 333, 'npi', 3, 1, 2, NULL, NULL);

INSERT INTO PERSONA (DNI, Nombre, PERSONA_DNI, unifamiliar, PISO_Letra, PISO_BLOQUE_CONSTRUCCION_IdConstruccion, PISO_Planta,
UNIFAMILIAR_CONSTRUCCION_idConstruccion, UNIFAMILIAR_CONSTRUCCION_CALLE_Nombre) VALUES (111, 'Esther', 222, 'npi', 3, 1, 2, 1, 'holi');
