USE EmpresaViveros;

/*INSERT INTO CLIENTES_FIDELIZADOS VALUES (111, 001, 123, 'Esther', 'Jorge', 'Paramio', NULL);*/
SELECT * FROM CLIENTES_FIDELIZADOS;

INSERT INTO EMPLEADOS VALUES (1, 333, 'Victoria', 'Parcial', NULL, NULL, NULL);
SELECT * FROM EMPLEADOS;

INSERT INTO PEDIDO VALUES (1, NULL, 111, 333);
SELECT * FROM PEDIDO;

INSERT INTO PRODUCTO VALUES (123, NULL, 'Flor', 3.0, 'Margarita', 10);
SELECT * FROM PRODUCTO;

INSERT INTO PEDIDO_has_PRODUCTO VALUES (1, 123, 4);
SELECT * FROM PEDIDO_has_PRODUCTO;
SELECT * FROM PRODUCTO;

INSERT INTO PEDIDO VALUES (2, NULL, 111, 333);
SELECT * FROM PEDIDO;

INSERT INTO PEDIDO_has_PRODUCTO VALUES (2, 123, 6);
SELECT * FROM PEDIDO_has_PRODUCTO;
SELECT * FROM PRODUCTO;

INSERT INTO PEDIDO VALUES (3, NULL, 111, 333);
INSERT INTO PEDIDO_has_PRODUCTO VALUES (3, 123, 1);

INSERT INTO PEDIDO VALUES (4, NULL, 111, 333);
INSERT INTO PEDIDO_has_PRODUCTO VALUES (4, 321, 5);



