CREATE DEFINER = CURRENT_USER TRIGGER `Catastro`.`trigger_no_viviendas_diferentes_before_insert` BEFORE INSERT ON `PERSONA` FOR EACH ROW
BEGIN
	IF NEW.PISO_Letra IS NOT NULL AND NEW.PISO_BLOQUE_CONSTRUCCION_idConstruccion IS NOT NULL AND NEW.PISO_Planta IS NOT NULL
	AND NEW.UNIFAMILIAR_CONSTRUCCION_idConstruccion IS NOT NULL AND NEW.UNIFAMILIAR_CONSTRUCCION_CALLE_Nombre IS NOT NULL THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Una persona no puede vivir en dos viviendas';
	END IF;
END